### ISSUE TITLE
Feature request: Support reverting changes in local changes panel

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1512] opened 2022-09-29 14:59 UTC
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

It will benefit users if we support reverting newly made changes per entities.

### Describe the solution you would like to see implemented

Suggested Design Plan:

- [ ] Support reverting changes per entity
- [ ] Compile graph after reverting

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment] 2022-09-29 21:23
Thanks for spotting this. This is a feature I would really like us to have. This is, however, a duplicate of https://github.com/finos/legend-studio/issues/954 though. I'll close this one and update the other one to make it more searchable.

Duplicate of #954

**Closed by akphi** 2022-09-29 21:23 UTC
Labels: Type: Feature Request, Studio Core Team, Application: Studio

**Comment by akphi** [comment] 2022-09-29 21:27
Duplicate of #954
