### ISSUE TITLE
Feature request: Support overloaded user-defined functions

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#686] opened 2021-11-17 19:37 UTC
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Overloaded user-defined functions have been allowed/supported in the backend. 
Studio needs to support this too.
Use the mode below.
```
function model::testInteger():Boolean[1]
{
  true;
}
function model::testInteger(input: Integer[1]):Boolean[1]
{
  true;
}
```

### Describe the solution you would like to see implemented

When checking the duplicated elements, for function, we should use path plus the whole function signature instead of path plus function name.

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment] 2022-10-31 23:00
Duplicate of #1211

**Closed by akphi** 2022-10-31 23:00 UTC
Labels: Type: Feature Request, Studio Core Team, Component: Graph Manager
