### ISSUE TITLE
Feature request: Provide ability to organize text mode code into multiple files

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#1657] opened 2022-11-07 07:45 UTC
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Provide ability to organize text mode code into multiple files

### Describe the solution you would like to see implemented

`ENGINE`
- [ ] `Engine` Change the response of `grammarToJson` api to return an array of grammar elements each corresponding to an entity instead of one single grammar text
- [ ] `Engine` Change the payload to `jsonToGrammar` api to take an array of grammar elements as an input each corresponding to an entity instead of one single grammar text
- [ ] add a new field to `SourceInformation` which stores the entity name so that we can do proper error handling when engine returns compilation errors
- [ ] Throw parsing error when user tries to add multiple elements in one file

`STUDIO`

- [ ] Show each entity in a different file in text mode
- [ ] `Think` about how to differentiate when you are in text mode and form mode as we have have tabs in both the modes 
        ( `MAYBE` Have a label in explorer tree that says which mode we are in )
- [ ] How to handle graph builder failure? `MAYBE` stay in form mode when we encounter this scenario and wait for the compilation to finish so that we have the `sourceInformation` of the compilation failure if ny exists so that we know which entity file to open when we re-direct to text mode.
- [ ] Support adding new packageable element from text mode. This can be made possible using snippet suggestions we have so that we can create a basic snippet. If no snippet exists we can just create an empty file
- [ ] How we are gonna do manual testing?
- [ ] We can show warnings specific to a file and specific to project in the warnings tab

### Contribution

- [x] I would like to work on this feature

**Comment by akphi** [comment] 2023-03-16 03:15
Closing this as we have done a PoC of this and realized that we cannot define the requirements properly for the feature, in particular, rename/refactor operation is hard as the user cannot do a simple text-replace anymore, and errors caused by this refactoring can spread across multiple files, making it harder for users to debug. Also, we need to think about what it means for section index, one strategy is for us to either flatten the import statements, or duplicate the import per file, but when re-assembling the individual file, we end up with duplication of sections.

**Closed by akphi** 2023-03-16 03:15 UTC
Labels: Type: Feature Request, Component: Text Mode
